version: '3.9'

services:
  springboot-app:
    build: ./springboot-app
    environment:
      DB_HOST: 172.31.23.125
      DB_PORT: 8005
      DB_NAME: viajes_db
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 8080
    networks: [backend]
    ports: ["8080:8080"]

  nestjs-app:
    build: ./nestjs-app
    environment:
      MONGO_USER: user
      MONGO_PASSWORD: utec2025
      MONGO_DB: sistema_equipaje
      MONGO_HOST: 172.31.23.125
      MONGO_PORT: 27017
      PORT: 8081
    networks: [backend]
    ports: ["8081:8081"]

  python-app:
    build: ./python-app
    environment:
        DB_USER: "user"
        DB_PASSWORD: "usuarios_db2025"
        DB_NAME: "usuarios_db"
        DB_HOST: 172.31.23.125
        DB_PORT: 3307
        PORT: 8082
    networks: [backend]
    ports: ["8082:8082"]

  orchestrator:
    build: ./orchestrator
    environment:
      API_VIAJE_URL: "http://springboot-app:8080/"
      API_EQUIPAJE_URL: "http://nestjs-app:8081/"
      API_USUARIOS_URL: "http://python-app:8082/"
    depends_on: [nestjs-app, springboot-app, python-app]
    networks: [backend]
    ports: ["8000:8000"]

networks:
  backend:
