version: '3.9'

services:
  springboot-app:
    build: ./springboot-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: viajes_db
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 8080
    depends_on: [postgres]
    networks: [backend]
    ports: ["5003:8080"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: viajes_db
      POSTGRES_PASSWORD: postgres
    volumes: [pg_data:/var/lib/postgresql/data]
    networks: [backend]

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks: [ backend ]
    ports: [ "8088:8080" ]

networks:
  backend:

volumes:
  pg_data:
