version: '3.9'

services:
  springboot-app:
    build: ./springboot-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: viajes_db
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 8080
    depends_on: [postgres]
    networks: [backend]
    ports: ["5003:8080"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: viajes_db
      POSTGRES_PASSWORD: postgres
    volumes: [pg_data:/var/lib/postgresql/data]
    networks: [backend]

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks: [ backend ]
    ports: [ "8088:8080" ]

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: utec2025
      MONGO_INITDB_DATABASE: sistema_equipaje
    volumes:
      - mongo_data:/data/db
    networks: [backend]
    ports: ["27017:27017"]

  nestjs-app:
    build: ./nestjs-app
    environment:
      MONGO_USER: user
      MONGO_PASSWORD: utec2025
      MONGO_DB: sistema_equipaje
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      PORT: 8081
    depends_on: [mongodb]
    networks: [backend]
    ports: [3750:8081]


networks:
  backend:

volumes:
  pg_data:
  mongo_data:
