version: '3.9'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: viajes_db
      POSTGRES_PASSWORD: postgres
    volumes: [pg_data:/var/lib/postgresql/data]
    networks: [backend]
    ports: ["8005:5432"]

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks: [ backend ]
    ports: [ "8088:8080" ]

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: utec2025
      MONGO_INITDB_DATABASE: sistema_equipaje
    volumes:
      - mongo_data:/data/db
    networks: [backend]
    ports: ["27017:27017"]

  mysql:
    image: mysql:8.0
    environment:
        DB_USER: "user"
        DB_PASSWORD: "usuarios_db2025"
        DB_NAME: "usuarios_db"
        DB_HOST: 172.31.23.125
        DB_PORT: 3307
        PORT: 8082
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [backend]
    ports: ["3306:3306"]

networks:
  backend:

volumes:
  pg_data:
  mongo_data:
  mysql_data:
